services:
  - type: web
    name: fastapi-ipynb-render
    runtime: python
    buildCommand: bash ./build.sh
    startCommand: uvicorn api.main:app --host 0.0.0.0 --port $PORT
    env:
      - key: PYTHON_VERSION
        value: 3.9
    envVars:
      - key: PYTHON_VERSION
        value: 3.9