services:
  - type: web
    name: your-app-name
    runtime: python
    buildCommand: |
      chmod +x build.sh
      chmod +x start.sh
      ./build.sh
    startCommand: ./start.sh
    env:
      - key: PYTHON_VERSION
        value: 3.9
      - key: PYTHONPATH
        value: .