services:
  - type: web
    name: your-app-name
    buildCommand: bash ./build.sh
    startCommand: uvicorn api.main:app --host 0.0.0.0 --port $PORT
    env:
      - key: PYTHON_VERSION
        value: 3.9